//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public int id_cargo { get; set; }
        public Nullable<int> id_puesto_nominal { get; set; }
        public Nullable<int> id_puesto_funcional { get; set; }
        public Nullable<int> id_estructura { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Estructura Estructura { get; set; }
        public virtual Puesto_Funcional Puesto_Funcional { get; set; }
    }
}
