//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    
    public partial class consulta_bandeja_vobo_Result8
    {
        public Nullable<int> id { get; set; }
        public string codigo { get; set; }
        public string nombre_proceso { get; set; }
        public Nullable<int> id_metodo_contratacion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<double> monto_goes { get; set; }
        public Nullable<double> monto_propio { get; set; }
        public Nullable<double> monto_proyectos { get; set; }
        public Nullable<double> monto_compensacion { get; set; }
        public Nullable<int> id_fuente_financiamiento { get; set; }
        public Nullable<int> id_tipo_fuente_financiamiento { get; set; }
        public Nullable<int> id_unidad_organizativa { get; set; }
        public Nullable<int> estado { get; set; }
        public int id_vobo { get; set; }
        public int tipo_vobo { get; set; }
        public string motivo_movimiento { get; set; }
        public string proceso_column { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
    }
}
