//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_presupuesto_anulacion
    {
        public int id_detalle_presupuesto_anulacion { get; set; }
        public Nullable<int> id_detalle_presupuesto { get; set; }
        public Nullable<int> id_vobo { get; set; }
        public string instruccion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual detalle_presupuesto detalle_presupuesto { get; set; }
        public virtual vobo vobo { get; set; }
    }
}
