//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Cargo = new HashSet<Cargo>();
        }
    
        public int id_empleado { get; set; }
        public string codigo_empleado { get; set; }
        public string foto_empleado { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string prefijo_academico { get; set; }
        public string correo_personal { get; set; }
        public string direccion_empleado { get; set; }
        public string telefono_personal { get; set; }
        public string celular_personal { get; set; }
        public Nullable<int> id_genero { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string codigo_pais { get; set; }
        public Nullable<int> id_departamento_nacimiento { get; set; }
        public Nullable<int> id_municipio_nacimiento { get; set; }
        public Nullable<int> id_ciudad_nacimiento { get; set; }
        public string nacionalidad { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> altura { get; set; }
        public Nullable<int> id_tiposangre { get; set; }
        public Nullable<int> id_discapacidad { get; set; }
        public Nullable<int> id_estadocivil { get; set; }
        public Nullable<int> id_tipocontrato { get; set; }
        public Nullable<int> id_tipocontratacion { get; set; }
        public string responsable { get; set; }
        public string telefono_responsable { get; set; }
        public string direccion_responsable { get; set; }
        public string correo_institucional { get; set; }
        public string telefono_institucional { get; set; }
        public string celular_institucional { get; set; }
        public string salario { get; set; }
        public string nombre_conyuge { get; set; }
        public string telefono_conyuge { get; set; }
        public Nullable<int> id_estado_usuario { get; set; }
        public Nullable<int> titular { get; set; }
        public Nullable<System.DateTime> fecha_contratacion { get; set; }
        public Nullable<int> id_detEstadoUsuario { get; set; }
        public Nullable<System.DateTime> fecha_renuncia { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public Nullable<int> id_profesion { get; set; }
        public Nullable<int> id_marcacion { get; set; }
        public string codigo_marcacion { get; set; }
        public Nullable<int> usuario_marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargo> Cargo { get; set; }
    }
}
