//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estructura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estructura()
        {
            this.Cargo = new HashSet<Cargo>();
        }
    
        public int id_estructura { get; set; }
        public Nullable<int> id_parent { get; set; }
        public string codigo { get; set; }
        public string nomenclatura { get; set; }
        public string nombre { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> id_periodo { get; set; }
        public Nullable<int> enlace_id_estructura { get; set; }
        public Nullable<int> id_nivel_organizativo { get; set; }
        public Nullable<int> orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargo> Cargo { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
