//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento_detalle_presupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimiento_detalle_presupuesto()
        {
            this.vobo = new HashSet<vobo>();
        }
    
        public int id_movimiento_detalle_presupuesto { get; set; }
        public Nullable<int> id_detalle_presupuesto { get; set; }
        public string nombre_proceso { get; set; }
        public Nullable<int> id_metodo_contratacion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<int> id_fuente_financiamiento { get; set; }
        public Nullable<int> id_unidad_organizativa { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
        public Nullable<int> estado { get; set; }
        public string motivo_movimiento { get; set; }
    
        public virtual detalle_presupuesto detalle_presupuesto { get; set; }
        public virtual fuente_financiamiento fuente_financiamiento { get; set; }
        public virtual metodo_contratacion metodo_contratacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vobo> vobo { get; set; }
    }
}
