//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento_vobo
    {
        public int id_movimiento_vobo { get; set; }
        public Nullable<int> id_vobo { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
        public Nullable<int> id_tipo_movimiento { get; set; }
        public Nullable<int> id_personal_vobo { get; set; }
        public Nullable<int> id_etapa_vobo { get; set; }
    
        public virtual etapa_vobo etapa_vobo { get; set; }
        public virtual personal_vobo personal_vobo { get; set; }
        public virtual tipo_movimiento tipo_movimiento { get; set; }
        public virtual vobo vobo { get; set; }
    }
}
