//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class registro_presupuestoEntities : DbContext
    {
        public registro_presupuestoEntities()
            : base("name=registro_presupuestoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalle_presupuesto> detalle_presupuesto { get; set; }
        public virtual DbSet<fuente_financiamiento> fuente_financiamiento { get; set; }
        public virtual DbSet<metodo_contratacion> metodo_contratacion { get; set; }
        public virtual DbSet<movimiento_detalle_presupuesto> movimiento_detalle_presupuesto { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<sub_menu> sub_menu { get; set; }
        public virtual DbSet<etapa_vobo> etapa_vobo { get; set; }
        public virtual DbSet<personal_vobo> personal_vobo { get; set; }
        public virtual DbSet<vobo> vobo { get; set; }
        public virtual DbSet<movimiento_vobo> movimiento_vobo { get; set; }
        public virtual DbSet<tipo_movimiento> tipo_movimiento { get; set; }
        public virtual DbSet<rol_usuario> rol_usuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<detalle_presupuesto_anulacion> detalle_presupuesto_anulacion { get; set; }
        public virtual DbSet<tipo_fuente_financiamiento> tipo_fuente_financiamiento { get; set; }
    
        public virtual ObjectResult<sp_persona_unidad_organizativa_Result> sp_persona_unidad_organizativa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_persona_unidad_organizativa_Result>("sp_persona_unidad_organizativa");
        }
    
        public virtual int EnvioNotificaciones(Nullable<int> tipo, string correos, string copias, string titulo, string mensaje, string copiasocultas)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            var correosParameter = correos != null ?
                new ObjectParameter("correos", correos) :
                new ObjectParameter("correos", typeof(string));
    
            var copiasParameter = copias != null ?
                new ObjectParameter("copias", copias) :
                new ObjectParameter("copias", typeof(string));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("mensaje", mensaje) :
                new ObjectParameter("mensaje", typeof(string));
    
            var copiasocultasParameter = copiasocultas != null ?
                new ObjectParameter("copiasocultas", copiasocultas) :
                new ObjectParameter("copiasocultas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnvioNotificaciones", tipoParameter, correosParameter, copiasParameter, tituloParameter, mensajeParameter, copiasocultasParameter);
        }
    
        public virtual ObjectResult<string> sp_obtener_personas_unidad_organizativa(Nullable<int> id_unidad_organizativa)
        {
            var id_unidad_organizativaParameter = id_unidad_organizativa.HasValue ?
                new ObjectParameter("id_unidad_organizativa", id_unidad_organizativa) :
                new ObjectParameter("id_unidad_organizativa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_obtener_personas_unidad_organizativa", id_unidad_organizativaParameter);
        }
    
        public virtual ObjectResult<string> sp_obtener_personas_vobo(Nullable<int> id_vobo)
        {
            var id_voboParameter = id_vobo.HasValue ?
                new ObjectParameter("id_vobo", id_vobo) :
                new ObjectParameter("id_vobo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_obtener_personas_vobo", id_voboParameter);
        }
    
        public virtual ObjectResult<consulta_bandeja_vobo_Result9> consulta_bandeja_vobo(Nullable<int> id_empleado)
        {
            var id_empleadoParameter = id_empleado.HasValue ?
                new ObjectParameter("id_empleado", id_empleado) :
                new ObjectParameter("id_empleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consulta_bandeja_vobo_Result9>("consulta_bandeja_vobo", id_empleadoParameter);
        }
    
        public virtual ObjectResult<sp_comprobante_Result> sp_comprobante(Nullable<int> id, Nullable<int> tipo_vobo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tipo_voboParameter = tipo_vobo.HasValue ?
                new ObjectParameter("tipo_vobo", tipo_vobo) :
                new ObjectParameter("tipo_vobo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_comprobante_Result>("sp_comprobante", idParameter, tipo_voboParameter);
        }
    
        public virtual ObjectResult<sp_consulta_procesos_compra_Result3> sp_consulta_procesos_compra(Nullable<int> id_unidad_organizativa)
        {
            var id_unidad_organizativaParameter = id_unidad_organizativa.HasValue ?
                new ObjectParameter("id_unidad_organizativa", id_unidad_organizativa) :
                new ObjectParameter("id_unidad_organizativa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_procesos_compra_Result3>("sp_consulta_procesos_compra", id_unidad_organizativaParameter);
        }
    
        public virtual ObjectResult<sp_consulta_procesos_movimiento_compra_Result3> sp_consulta_procesos_movimiento_compra(Nullable<int> id_detalle_presupuesto)
        {
            var id_detalle_presupuestoParameter = id_detalle_presupuesto.HasValue ?
                new ObjectParameter("id_detalle_presupuesto", id_detalle_presupuesto) :
                new ObjectParameter("id_detalle_presupuesto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_procesos_movimiento_compra_Result3>("sp_consulta_procesos_movimiento_compra", id_detalle_presupuestoParameter);
        }
    
        public virtual ObjectResult<sp_general_proceso_compra_Result2> sp_general_proceso_compra(Nullable<int> anio)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_general_proceso_compra_Result2>("sp_general_proceso_compra", anioParameter);
        }
    
        public virtual ObjectResult<sp_general_proceso_compra_auditoria_Result2> sp_general_proceso_compra_auditoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_general_proceso_compra_auditoria_Result2>("sp_general_proceso_compra_auditoria");
        }
    }
}
