//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class registro_presupuestoEntities : DbContext
    {
        public registro_presupuestoEntities()
            : base("name=registro_presupuestoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalle_presupuesto> detalle_presupuesto { get; set; }
        public virtual DbSet<fuente_financiamiento> fuente_financiamiento { get; set; }
        public virtual DbSet<metodo_contratacion> metodo_contratacion { get; set; }
        public virtual DbSet<movimiento_detalle_presupuesto> movimiento_detalle_presupuesto { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<sub_menu> sub_menu { get; set; }
        public virtual DbSet<etapa_vobo> etapa_vobo { get; set; }
        public virtual DbSet<personal_vobo> personal_vobo { get; set; }
        public virtual DbSet<vobo> vobo { get; set; }
        public virtual DbSet<movimiento_vobo> movimiento_vobo { get; set; }
        public virtual DbSet<tipo_movimiento> tipo_movimiento { get; set; }
    
        public virtual ObjectResult<consulta_bandeja_vobo_Result1> consulta_bandeja_vobo(Nullable<int> id_empleado)
        {
            var id_empleadoParameter = id_empleado.HasValue ?
                new ObjectParameter("id_empleado", id_empleado) :
                new ObjectParameter("id_empleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consulta_bandeja_vobo_Result1>("consulta_bandeja_vobo", id_empleadoParameter);
        }
    }
}
