//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class registro_presupuestoEntities : DbContext
    {
        public registro_presupuestoEntities()
            : base("name=registro_presupuestoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalle_presupuesto> detalle_presupuesto { get; set; }
        public virtual DbSet<fuente_financiamiento> fuente_financiamiento { get; set; }
        public virtual DbSet<metodo_contratacion> metodo_contratacion { get; set; }
        public virtual DbSet<movimiento_detalle_presupuesto> movimiento_detalle_presupuesto { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<sub_menu> sub_menu { get; set; }
        public virtual DbSet<etapa_vobo> etapa_vobo { get; set; }
        public virtual DbSet<personal_vobo> personal_vobo { get; set; }
        public virtual DbSet<vobo> vobo { get; set; }
    }
}
