//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rrhhEntities : DbContext
    {
        public rrhhEntities()
            : base("name=rrhhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Puesto_Funcional> Puesto_Funcional { get; set; }
        public virtual DbSet<Estructura> Estructura { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
    }
}
