//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    
    public partial class sp_consulta_procesos_compra_Result1
    {
        public int id_detalle_presupuesto { get; set; }
        public string codigo { get; set; }
        public string nombre_proceso { get; set; }
        public Nullable<int> id_metodo_contratacion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<int> id_fuente_financiamiento { get; set; }
        public Nullable<int> id_unidad_organizativa { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<double> monto_goes { get; set; }
        public Nullable<double> monto_propio { get; set; }
        public Nullable<double> monto_proyectos { get; set; }
        public Nullable<double> monto_compensacion { get; set; }
        public string metodo_contratacion { get; set; }
        public string fuente_financiamiento { get; set; }
        public string estatus_proceso { get; set; }
        public string estatus_general { get; set; }
    }
}
