//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_menu
    {
        public int id_sub_menu { get; set; }
        public string sub_menu_icono { get; set; }
        public string sub_menu_nombre { get; set; }
        public string accion { get; set; }
        public string controlador { get; set; }
        public Nullable<int> id_menu { get; set; }
        public Nullable<int> orden { get; set; }
        public string id_rol { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual menu menu { get; set; }
    }
}
