//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vobo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vobo()
        {
            this.movimiento_vobo = new HashSet<movimiento_vobo>();
        }
    
        public int id_vobo { get; set; }
        public Nullable<int> id_personal_vobo { get; set; }
        public Nullable<int> id_detalle_presupuesto { get; set; }
        public Nullable<int> id_etapa_vobo { get; set; }
        public string instruccion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual detalle_presupuesto detalle_presupuesto { get; set; }
        public virtual etapa_vobo etapa_vobo { get; set; }
        public virtual personal_vobo personal_vobo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_vobo> movimiento_vobo { get; set; }
    }
}
